name: CI [ui]

on: [push]

jobs:
  build-ui:
    name: Build [ui]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./ui
        run: npm install -g pnpm && pnpm install

      - name: Copy .env.example files
        shell: bash
        working-directory: ./ui
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      - name: Check Format
        working-directory: ./ui
        run: pnpm format:check

      - name: Run Checks (Lint + Typecheck)
        working-directory: ./ui
        run: pnpm check

      - name: Build
        working-directory: ./ui
        run: pnpm build